"""ajout de table restaurant_activation_history

Revision ID: 258d1516932a
Revises: 4c34912cb2de
Create Date: 2026-06-04 14:24:41.307309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258d1516932a'

down_revision: Union[str, None] = '4c34912cb2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approboisson', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('approcuisine', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('casier', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('commande', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('commandearticle', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('condiment', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.add_column('unite', sa.Column('isActive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unite', 'isActive')
    op.drop_column('condiment', 'isActive')
    op.drop_column('commandearticle', 'isActive')
    op.drop_column('commande', 'isActive')
    op.drop_column('casier', 'isActive')
    op.drop_column('approcuisine', 'isActive')
    op.drop_column('approboisson', 'isActive')
    # ### end Alembic commands ###
