"""creation

Revision ID: 4c34912cb2de
Revises: 
Create Date: 2026-05-29 15:22:05.173004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c34912cb2de'

down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('restaurant', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('restaurant', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('restaurant', 'ownerId',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('restaurant', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('restaurant', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('restaurant', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key('fk_restaurant_owner', 'restaurant', 'user', ['ownerId'], ['id'], use_alter=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # op.drop_constraint('fk_restaurant_owner', 'restaurant', type_='foreignkey') # This line was causing issues in some environments or was commented out in my previous read
    op.alter_column('restaurant', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('restaurant', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('restaurant', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('restaurant', 'ownerId',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('restaurant', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('restaurant', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('restaurant', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
