"""refactor menu boissons

Revision ID: aa79f2e749d9
Revises: 5d168195c2c2
Create Date: 2026-09-24 14:02:41.281222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa79f2e749d9'

down_revision: Union[str, None] = '5d168195c2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuboisson', sa.Column('menuBoissonFamilleId', sa.UUID(), nullable=False))
    op.alter_column('menuboisson', 'boissonId',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('menuboisson', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('menuboisson', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'menuboisson', 'menuboissonfamille', ['menuBoissonFamilleId'], ['id'])
    op.drop_column('menuboisson', 'imageUrl')
    op.drop_column('menuboisson', 'ordre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuboisson', sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menuboisson', sa.Column('imageUrl', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menuboisson', type_='foreignkey')
    op.alter_column('menuboisson', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('menuboisson', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('menuboisson', 'boissonId',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('menuboisson', 'menuBoissonFamilleId')
    # ### end Alembic commands ###
