"""initial migration

Revision ID: ef54318de692
Revises:
Create Date: 2026-05-29 13:10:58.147073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef54318de692'

down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodepayment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nomMethode', sa.Enum('MOMO', 'FEDAPAY', 'CASH', name='methodepaiementenum'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.create_table('restaurant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('ownerId', sa.UUID(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boisson',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('nomBoisson', sa.String(length=255), nullable=True),
    sa.Column('contenance', sa.Enum('CL55', 'CL33', name='boissoncontenance'), nullable=True),
    sa.Column('prixVente', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_restaurant_owner', 'restaurant', 'user', ['ownerId'], ['id'])
    op.create_table('casier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('typeCasier', sa.Enum('T12', 'T20', 'T24', name='casiertype'), nullable=True),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condiment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('nomcondiment', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('nomRepas', sa.String(length=255), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolepermission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roleId', sa.UUID(), nullable=True),
    sa.Column('permissionId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permissionId'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unite', sa.Enum('KG', 'LITRES', name='unitetype'), nullable=True),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('emailVerified', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('providerAccountId', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approboisson',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('boissonId', sa.UUID(), nullable=True),
    sa.Column('casierId', sa.UUID(), nullable=True),
    sa.Column('prixAchat', sa.Float(), nullable=True),
    sa.Column('nbreCasier', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boissonId'], ['boisson.id'], ),
    sa.ForeignKeyConstraint(['casierId'], ['casier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approcuisine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condimentId', sa.UUID(), nullable=True),
    sa.Column('uniteId', sa.UUID(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('qte', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condimentId'], ['condiment.id'], ),
    sa.ForeignKeyConstraint(['uniteId'], ['unite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commande',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('numeroCommande', sa.String(length=255), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='commandestatut'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commande_numeroCommande'), 'commande', ['numeroCommande'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('userrole',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('roleId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandearticle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commandeId', sa.UUID(), nullable=True),
    sa.Column('boissonId', sa.UUID(), nullable=True),
    sa.Column('repasId', sa.UUID(), nullable=True),
    sa.Column('qte', sa.Integer(), nullable=True),
    sa.Column('prixUnitaire', sa.Float(), nullable=True),
    sa.Column('sousTotal', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boissonId'], ['boisson.id'], ),
    sa.ForeignKeyConstraint(['commandeId'], ['commande.id'], ),
    sa.ForeignKeyConstraint(['repasId'], ['repas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reglementfacture',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=True),
    sa.Column('commandeId', sa.UUID(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('methodeId', sa.UUID(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commandeId'], ['commande.id'], ),
    sa.ForeignKeyConstraint(['methodeId'], ['methodepayment.id'], ),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_restaurant_owner', 'restaurant', type_='foreignkey')
    op.drop_table('reglementfacture')
    op.drop_table('commandearticle')
    op.drop_table('userrole')
    op.drop_table('session')
    op.drop_index(op.f('ix_commande_numeroCommande'), table_name='commande')
    op.drop_table('commande')
    op.drop_table('approcuisine')
    op.drop_table('approboisson')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('unite')
    op.drop_table('rolepermission')
    op.drop_table('repas')
    op.drop_table('condiment')
    op.drop_table('casier')
    op.drop_table('boisson')
    op.drop_table('verification')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_table('permission')
    op.drop_table('methodepayment')
    # ### end Alembic commands ###
