"""create restaurant_user table

Revision ID: f58b5a3c56a1
Revises: 2eb6ff81b3b3
Create Date: 2026-06-12 00:03:52.750019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58b5a3c56a1'

down_revision: Union[str, None] = '2eb6ff81b3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantuser',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('restaurantId', sa.UUID(), nullable=False),
    sa.Column('roleId', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', name='userrestaurantstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_foreign_key('fk_restaurant_owner', 'restaurant', 'user', ['ownerId'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_restaurant_owner', 'restaurant', type_='foreignkey')
    op.drop_table('restaurantuser')
    # ### end Alembic commands ###
